"""Config file"""
TOKEN = ''
DB_ADDRESS = '127.0.0.1'
DB_NAME = 'TabaBotDB'

PIXIV_HISTORY_SIZE = 25
PIXIV_SHOW_EMBED_ILLUST = False
USE_SELENIUM = False
VOLUME_LOCK = False
SAFETY = False

WAVELINK_HOST = '127.0.0.1'
WAVELINK_PORT = 2333
WAVELINK_PASSWORD = ''
SPOTIFY_CLIENT_ID = ''
SPOTIFY_CLIENT_SECRET = ''
SAUCENAO_TOKEN = ''
YOUTUBE_API_TOKEN = ''
